builds: 
  - all
caches:
  - ghcr.io;ItzEmoji/cache-action-test

compression: zstd
workers: 50
signing-key: NIX_SIGNING_KEY
release-repo: ItzEmoji/aeroflare-test
upstream-cache:
  - https://cache.nixos.org
