name: test-action
on:
  push:
    branches:
      - main
jobs:
  cache:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: ItzEmoji/aeroflare-test@v1
        with:
          cache: ghcr.io;itzemoji/cache-action-test
          builds: |
            github:ItzEmoji/nvim#default
          upstream-cache: https://cache.nixos.org
        env:
          AEROFLARE_REPO: ItzEmoji/aeroflare-test
