name: test-action
on:
  push:
    branches:
      - main
jobs:
  cache:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: ItzEmoji/aeroflare@v1
        with:
          cache: ghcr.io;itzemoji/nix-packages-cache
          builds: |
            github:ItzEmoji/nvim#default
          upstream-cache: https://cache.nixos.org
        env:
          NIX_SIGNING_KEY: ${{ secrets.NIX_SIGNING_KEY }}
